baseURL = "https://nicetrygee.github.io/mutable-state/"   
languageCode = "en-gb"
title = "mutable state"

[params]
  author = "mutable state"
  description = "Engineering, management, and the space between."

[permalinks]
  posts = "/:slug/"
